version: "3.3"

services:
  api:
    build: .
    command: /start-reload.sh
    environment:
      - SHELVE_PATH=/app/db/shelve.db
    ports: 
      - 8000:80
    volumes:
      - ./app:/app/app
      - db:/app/db

volumes:
  db: